version: '3'

services:
  orm:
    build: .
    image: orm_image
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/app
    env_file:
      environment/local
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5432:5432
  tests:
    build:
      dockerfile: Dockerfile-test
      context: .
    command: bash -c "prospector && pytest --cov=instances/management/commands -vv"
    volumes:
      - .:/app
    env_file:
      environment/local
    depends_on:
      - db
